from abc import ABC, abstractmethod
from typing import Dict, Any
import os
import json

class LLMProvider(ABC):
    @abstractmethod
    def generate_structured_response(self, prompt: str, context: str) -> Dict[str, Any]:
        pass

class OpenAILLMProvider(LLMProvider):
    def __init__(self, api_key: str = None, model: str = "gpt-4-turbo"):
        self.api_key = api_key or os.getenv("OPENAI_API_KEY")
        self.model = model
        if self.api_key:
            from openai import OpenAI
            self.client = OpenAI(api_key=self.api_key)
        else:
            self.client = None
            
    def generate_structured_response(self, prompt: str, context: str) -> Dict[str, Any]:
        if not self.client:
            raise ValueError("OpenAI API key not configured")
            
        messages = [
            {"role": "system", "content": "You are an investigation assistant. Use only the supplied evidence. Format your output strictly as JSON with the following keys: 'answer' (string), 'key_findings' (list of strings), 'uncertainties' (list of strings), 'evidence' (list of objects with 'citation_id', 'source_type', 'source_id', 'case_id', 'excerpt', 'relevance'), 'confidence' (string), 'suggested_follow_up_questions' (list of strings)."},
            {"role": "user", "content": f"Context: {context}\n\nQuestion/Prompt: {prompt}"}
        ]
        
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=messages,
                response_format={"type": "json_object"}
            )
            return json.loads(response.choices[0].message.content)
        except Exception as e:
            return {
                "answer": f"LLM Error: {str(e)}",
                "key_findings": [],
                "uncertainties": ["Provider unavailable"],
                "evidence": [],
                "confidence": "LOW",
                "suggested_follow_up_questions": []
            }

class LocalLLMProvider(LLMProvider):
    def __init__(self, model_name: str = "HuggingFaceTB/SmolLM2-135M"):
        # We instantiate on first use to speed up boot if not needed
        self.model_name = model_name
        self._pipe = None
        
    @property
    def pipe(self):
        if self._pipe is None:
            from transformers import pipeline
            self._pipe = pipeline("text-generation", model=self.model_name, max_new_tokens=50)
        return self._pipe

    def generate_structured_response(self, prompt: str, context: str) -> Dict[str, Any]:
        if not context.strip():
            return {
                "answer": "Insufficient evidence to answer this question.",
                "key_findings": [],
                "uncertainties": ["Missing data"],
                "evidence": [],
                "confidence": "LOW",
                "suggested_follow_up_questions": []
            }
            
        sys_prompt = "Answer the question based only on the evidence. Keep it short."
        text_input = f"{sys_prompt}\n\nEvidence:\n{context}\n\nQuestion: {prompt}\n\nAnswer:"
        
        try:
            result = self.pipe(text_input, do_sample=False)[0]["generated_text"]
            # Extract only the newly generated text
            answer = result[len(text_input):].strip().split('\n')[0]
            if not answer:
                answer = "No conclusive answer generated by local model."
                
            return {
                "answer": answer,
                "key_findings": ["Local inference successful"],
                "uncertainties": [],
                "evidence": [], # we rely on backend for valid citations
                "confidence": "MEDIUM",
                "suggested_follow_up_questions": []
            }
        except Exception as e:
             return {
                "answer": f"Local LLM Error: {str(e)}",
                "key_findings": [],
                "uncertainties": ["Model inference failed"],
                "evidence": [],
                "confidence": "LOW",
                "suggested_follow_up_questions": []
            }

def get_llm_provider() -> LLMProvider:
    if os.getenv("OPENAI_API_KEY"):
        return OpenAILLMProvider()
    return LocalLLMProvider()
