"""Phase 4 Transaction and Events

Revision ID: 0592eaecfa0b
Revises: dafb5941ad10
Create Date: 2026-10-01 13:16:26.107840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0592eaecfa0b'
down_revision: Union[str, Sequence[str], None] = 'dafb5941ad10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dead_letter_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('consumer_name', sa.String(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_events_event_id'), 'dead_letter_events', ['event_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('aggregate_type', sa.String(), nullable=False),
    sa.Column('aggregate_id', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('causation_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_causation_id'), 'outbox_events', ['causation_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_correlation_id'), 'outbox_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_table('processed_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('consumer_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_events_consumer_name'), 'processed_events', ['consumer_name'], unique=False)
    op.create_index(op.f('ix_processed_events_event_id'), 'processed_events', ['event_id'], unique=False)
    op.add_column('transaction_events', sa.Column('schema_version', sa.Integer(), nullable=False))
    op.add_column('transaction_events', sa.Column('correlation_id', sa.String(), nullable=True))
    op.add_column('transaction_events', sa.Column('causation_id', sa.String(), nullable=True))
    op.add_column('transaction_events', sa.Column('payload', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_transaction_events_causation_id'), 'transaction_events', ['causation_id'], unique=False)
    op.create_index(op.f('ix_transaction_events_correlation_id'), 'transaction_events', ['correlation_id'], unique=False)
    op.add_column('transactions', sa.Column('external_transaction_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('correlation_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('channel', sa.String(), nullable=True))
    op.create_index(op.f('ix_transactions_correlation_id'), 'transactions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_transactions_external_transaction_id'), 'transactions', ['external_transaction_id'], unique=False)
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_external_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_correlation_id'), table_name='transactions')
    op.drop_column('transactions', 'channel')
    op.drop_column('transactions', 'correlation_id')
    op.drop_column('transactions', 'idempotency_key')
    op.drop_column('transactions', 'external_transaction_id')
    op.drop_index(op.f('ix_transaction_events_correlation_id'), table_name='transaction_events')
    op.drop_index(op.f('ix_transaction_events_causation_id'), table_name='transaction_events')
    op.drop_column('transaction_events', 'payload')
    op.drop_column('transaction_events', 'causation_id')
    op.drop_column('transaction_events', 'correlation_id')
    op.drop_column('transaction_events', 'schema_version')
    op.drop_index(op.f('ix_processed_events_event_id'), table_name='processed_events')
    op.drop_index(op.f('ix_processed_events_consumer_name'), table_name='processed_events')
    op.drop_table('processed_events')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_correlation_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_causation_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_dead_letter_events_event_id'), table_name='dead_letter_events')
    op.drop_table('dead_letter_events')
    # ### end Alembic commands ###
