"""Phase 10 Merchant and Agent Profiles

Revision ID: 13d24ea95645
Revises: 261f0e1060d2
Create Date: 2026-10-01 14:16:03.319002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d24ea95645'
down_revision: Union[str, Sequence[str], None] = '261f0e1060d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_profiles', sa.Column('profile_version', sa.Integer(), nullable=False))
    op.add_column('agent_profiles', sa.Column('observation_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agent_profiles', sa.Column('observation_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agent_profiles', sa.Column('transaction_count', sa.Integer(), nullable=False))
    op.add_column('agent_profiles', sa.Column('transaction_volume', sa.Float(), nullable=False))
    op.add_column('agent_profiles', sa.Column('unique_customer_count', sa.Integer(), nullable=False))
    op.add_column('agent_profiles', sa.Column('average_transaction_amount', sa.Float(), nullable=False))
    op.add_column('agent_profiles', sa.Column('median_transaction_amount', sa.Float(), nullable=False))
    op.add_column('agent_profiles', sa.Column('largest_transaction_amount', sa.Float(), nullable=False))
    op.add_column('agent_profiles', sa.Column('successful_transaction_count', sa.Integer(), nullable=False))
    op.add_column('agent_profiles', sa.Column('failed_transaction_count', sa.Integer(), nullable=False))
    op.add_column('agent_profiles', sa.Column('reversal_count', sa.Integer(), nullable=False))
    op.add_column('agent_profiles', sa.Column('customer_concentration', sa.Float(), nullable=False))
    op.add_column('agent_profiles', sa.Column('location_consistency', sa.Float(), nullable=False))
    op.add_column('agent_profiles', sa.Column('data_sufficiency', sa.String(), nullable=False))
    op.add_column('agent_profiles', sa.Column('last_calculated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_unique_constraint(None, 'agent_profiles', ['agent_id'])
    op.add_column('merchant_profiles', sa.Column('profile_version', sa.Integer(), nullable=False))
    op.add_column('merchant_profiles', sa.Column('observation_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('merchant_profiles', sa.Column('observation_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('merchant_profiles', sa.Column('transaction_count', sa.Integer(), nullable=False))
    op.add_column('merchant_profiles', sa.Column('transaction_volume', sa.Float(), nullable=False))
    op.add_column('merchant_profiles', sa.Column('unique_customer_count', sa.Integer(), nullable=False))
    op.add_column('merchant_profiles', sa.Column('average_transaction_amount', sa.Float(), nullable=False))
    op.add_column('merchant_profiles', sa.Column('median_transaction_amount', sa.Float(), nullable=False))
    op.add_column('merchant_profiles', sa.Column('largest_transaction_amount', sa.Float(), nullable=False))
    op.add_column('merchant_profiles', sa.Column('successful_transaction_count', sa.Integer(), nullable=False))
    op.add_column('merchant_profiles', sa.Column('failed_transaction_count', sa.Integer(), nullable=False))
    op.add_column('merchant_profiles', sa.Column('reversal_count', sa.Integer(), nullable=False))
    op.add_column('merchant_profiles', sa.Column('refund_count', sa.Integer(), nullable=False))
    op.add_column('merchant_profiles', sa.Column('customer_concentration', sa.Float(), nullable=False))
    op.add_column('merchant_profiles', sa.Column('data_sufficiency', sa.String(), nullable=False))
    op.add_column('merchant_profiles', sa.Column('last_calculated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_unique_constraint(None, 'merchant_profiles', ['merchant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'merchant_profiles', type_='unique')
    op.drop_column('merchant_profiles', 'last_calculated_at')
    op.drop_column('merchant_profiles', 'data_sufficiency')
    op.drop_column('merchant_profiles', 'customer_concentration')
    op.drop_column('merchant_profiles', 'refund_count')
    op.drop_column('merchant_profiles', 'reversal_count')
    op.drop_column('merchant_profiles', 'failed_transaction_count')
    op.drop_column('merchant_profiles', 'successful_transaction_count')
    op.drop_column('merchant_profiles', 'largest_transaction_amount')
    op.drop_column('merchant_profiles', 'median_transaction_amount')
    op.drop_column('merchant_profiles', 'average_transaction_amount')
    op.drop_column('merchant_profiles', 'unique_customer_count')
    op.drop_column('merchant_profiles', 'transaction_volume')
    op.drop_column('merchant_profiles', 'transaction_count')
    op.drop_column('merchant_profiles', 'observation_end')
    op.drop_column('merchant_profiles', 'observation_start')
    op.drop_column('merchant_profiles', 'profile_version')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'agent_profiles', type_='unique')
    op.drop_column('agent_profiles', 'last_calculated_at')
    op.drop_column('agent_profiles', 'data_sufficiency')
    op.drop_column('agent_profiles', 'location_consistency')
    op.drop_column('agent_profiles', 'customer_concentration')
    op.drop_column('agent_profiles', 'reversal_count')
    op.drop_column('agent_profiles', 'failed_transaction_count')
    op.drop_column('agent_profiles', 'successful_transaction_count')
    op.drop_column('agent_profiles', 'largest_transaction_amount')
    op.drop_column('agent_profiles', 'median_transaction_amount')
    op.drop_column('agent_profiles', 'average_transaction_amount')
    op.drop_column('agent_profiles', 'unique_customer_count')
    op.drop_column('agent_profiles', 'transaction_volume')
    op.drop_column('agent_profiles', 'transaction_count')
    op.drop_column('agent_profiles', 'observation_end')
    op.drop_column('agent_profiles', 'observation_start')
    op.drop_column('agent_profiles', 'profile_version')
    # ### end Alembic commands ###
