"""Phase 9 Financial Intelligence Tables

Revision ID: 261f0e1060d2
Revises: 37543ba34724
Create Date: 2026-10-01 14:07:08.963286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261f0e1060d2'
down_revision: Union[str, Sequence[str], None] = '37543ba34724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_profiles', sa.Column('profile_version', sa.Integer(), nullable=False))
    op.add_column('financial_profiles', sa.Column('observation_start', sa.DateTime(timezone=True), nullable=True))
    op.add_column('financial_profiles', sa.Column('observation_end', sa.DateTime(timezone=True), nullable=True))
    op.add_column('financial_profiles', sa.Column('total_inflow', sa.Float(), nullable=False))
    op.add_column('financial_profiles', sa.Column('total_outflow', sa.Float(), nullable=False))
    op.add_column('financial_profiles', sa.Column('net_cash_flow', sa.Float(), nullable=False))
    op.add_column('financial_profiles', sa.Column('average_daily_inflow', sa.Float(), nullable=False))
    op.add_column('financial_profiles', sa.Column('average_daily_outflow', sa.Float(), nullable=False))
    op.add_column('financial_profiles', sa.Column('inflow_transaction_count', sa.Integer(), nullable=False))
    op.add_column('financial_profiles', sa.Column('outflow_transaction_count', sa.Integer(), nullable=False))
    op.add_column('financial_profiles', sa.Column('cash_flow_volatility', sa.Float(), nullable=False))
    op.add_column('financial_profiles', sa.Column('financial_stability_score', sa.Float(), nullable=False))
    op.add_column('financial_profiles', sa.Column('liquidity_score', sa.Float(), nullable=False))
    op.add_column('financial_profiles', sa.Column('financial_health_score', sa.String(), nullable=False))
    op.add_column('financial_profiles', sa.Column('data_sufficiency', sa.String(), nullable=False))
    op.add_column('financial_profiles', sa.Column('forecast_data', sa.JSON(), nullable=True))
    op.add_column('financial_profiles', sa.Column('last_calculated_at', sa.DateTime(timezone=True), nullable=False))
    op.create_unique_constraint(None, 'financial_profiles', ['customer_id'])
    op.drop_column('financial_profiles', 'risk_rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_profiles', sa.Column('risk_rating', sa.VARCHAR(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'financial_profiles', type_='unique')
    op.drop_column('financial_profiles', 'last_calculated_at')
    op.drop_column('financial_profiles', 'forecast_data')
    op.drop_column('financial_profiles', 'data_sufficiency')
    op.drop_column('financial_profiles', 'financial_health_score')
    op.drop_column('financial_profiles', 'liquidity_score')
    op.drop_column('financial_profiles', 'financial_stability_score')
    op.drop_column('financial_profiles', 'cash_flow_volatility')
    op.drop_column('financial_profiles', 'outflow_transaction_count')
    op.drop_column('financial_profiles', 'inflow_transaction_count')
    op.drop_column('financial_profiles', 'average_daily_outflow')
    op.drop_column('financial_profiles', 'average_daily_inflow')
    op.drop_column('financial_profiles', 'net_cash_flow')
    op.drop_column('financial_profiles', 'total_outflow')
    op.drop_column('financial_profiles', 'total_inflow')
    op.drop_column('financial_profiles', 'observation_end')
    op.drop_column('financial_profiles', 'observation_start')
    op.drop_column('financial_profiles', 'profile_version')
    # ### end Alembic commands ###
