"""Phase 8 Customer Intelligence Tables

Revision ID: 37543ba34724
Revises: de7a68e63472
Create Date: 2026-10-01 13:58:32.014066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37543ba34724'
down_revision: Union[str, Sequence[str], None] = 'de7a68e63472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_profiles', sa.Column('profile_version', sa.Integer(), nullable=False))
    op.add_column('customer_profiles', sa.Column('first_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customer_profiles', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customer_profiles', sa.Column('transaction_count', sa.Integer(), nullable=False))
    op.add_column('customer_profiles', sa.Column('transaction_volume', sa.Float(), nullable=False))
    op.add_column('customer_profiles', sa.Column('average_transaction_amount', sa.Float(), nullable=False))
    op.add_column('customer_profiles', sa.Column('unique_beneficiary_count', sa.Integer(), nullable=False))
    op.add_column('customer_profiles', sa.Column('unique_device_count', sa.Integer(), nullable=False))
    op.add_column('customer_profiles', sa.Column('active_days', sa.Integer(), nullable=False))
    op.add_column('customer_profiles', sa.Column('lifecycle_state', sa.String(), nullable=False))
    op.add_column('customer_profiles', sa.Column('behavioral_stability', sa.String(), nullable=False))
    op.add_column('customer_profiles', sa.Column('engagement_score', sa.Float(), nullable=False))
    op.create_unique_constraint(None, 'customer_profiles', ['customer_id'])
    op.add_column('customer_segments', sa.Column('version', sa.Integer(), nullable=False))
    op.add_column('customer_segments', sa.Column('evidence', sa.String(), nullable=True))
    op.add_column('customer_segments', sa.Column('effective_timestamp', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_segments', 'effective_timestamp')
    op.drop_column('customer_segments', 'evidence')
    op.drop_column('customer_segments', 'version')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'customer_profiles', type_='unique')
    op.drop_column('customer_profiles', 'engagement_score')
    op.drop_column('customer_profiles', 'behavioral_stability')
    op.drop_column('customer_profiles', 'lifecycle_state')
    op.drop_column('customer_profiles', 'active_days')
    op.drop_column('customer_profiles', 'unique_device_count')
    op.drop_column('customer_profiles', 'unique_beneficiary_count')
    op.drop_column('customer_profiles', 'average_transaction_amount')
    op.drop_column('customer_profiles', 'transaction_volume')
    op.drop_column('customer_profiles', 'transaction_count')
    op.drop_column('customer_profiles', 'last_activity_at')
    op.drop_column('customer_profiles', 'first_activity_at')
    op.drop_column('customer_profiles', 'profile_version')
    # ### end Alembic commands ###
