"""phase_12_copilot

Revision ID: 878268a9de09
Revises: 8a106be123ee
Create Date: 2026-10-01 15:12:40.980871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '878268a9de09'
down_revision: Union[str, Sequence[str], None] = '8a106be123ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copilot_conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('investigator_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['investigator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('copilot_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('feedback', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['copilot_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('copilot_citations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('excerpt', sa.String(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['copilot_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ai_chunks', sa.Column('chunk_index', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('ai_chunks_document_id_fkey'), 'ai_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'ai_chunks', 'ai_documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.add_column('ai_documents', sa.Column('source_type', sa.String(), nullable=True))
    op.add_column('ai_documents', sa.Column('source_id', sa.String(), nullable=True))
    op.add_column('ai_documents', sa.Column('entity_type', sa.String(), nullable=True))
    op.add_column('ai_documents', sa.Column('entity_id', sa.String(), nullable=True))
    op.add_column('ai_documents', sa.Column('case_id', sa.String(), nullable=True))
    op.add_column('ai_documents', sa.Column('content', sa.String(), nullable=True))
    op.add_column('ai_documents', sa.Column('access_scope', sa.String(), nullable=True))
    op.alter_column('ai_documents', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_ai_documents_source_id'), 'ai_documents', ['source_id'], unique=False)
    op.create_index(op.f('ix_ai_documents_source_type'), 'ai_documents', ['source_type'], unique=False)
    op.create_foreign_key(None, 'ai_documents', 'investigation_cases', ['case_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'ai_documents', type_='foreignkey')
    op.drop_index(op.f('ix_ai_documents_source_type'), table_name='ai_documents')
    op.drop_index(op.f('ix_ai_documents_source_id'), table_name='ai_documents')
    op.alter_column('ai_documents', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('ai_documents', 'access_scope')
    op.drop_column('ai_documents', 'content')
    op.drop_column('ai_documents', 'case_id')
    op.drop_column('ai_documents', 'entity_id')
    op.drop_column('ai_documents', 'entity_type')
    op.drop_column('ai_documents', 'source_id')
    op.drop_column('ai_documents', 'source_type')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'ai_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('ai_chunks_document_id_fkey'), 'ai_chunks', 'ai_documents', ['document_id'], ['id'])
    op.drop_column('ai_chunks', 'chunk_index')
    op.drop_table('copilot_citations')
    op.drop_table('copilot_messages')
    op.drop_table('copilot_conversations')
    # ### end Alembic commands ###
