"""clean phase 11 models

Revision ID: 8a106be123ee
Revises: 13d24ea95645
Create Date: 2026-10-01 14:46:55.828557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a106be123ee'
down_revision: Union[str, Sequence[str], None] = '13d24ea95645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('primary_entity_type', sa.String(), nullable=False),
    sa.Column('primary_entity_id', sa.String(), nullable=False),
    sa.Column('assigned_investigator_id', sa.String(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_type', sa.String(), nullable=True),
    sa.Column('resolution_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_investigator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_cases_case_number'), 'investigation_cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_investigation_cases_primary_entity_id'), 'investigation_cases', ['primary_entity_id'], unique=False)
    op.create_index(op.f('ix_investigation_cases_primary_entity_type'), 'investigation_cases', ['primary_entity_type'], unique=False)
    op.create_table('alert_correlation_groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('group_key', sa.String(), nullable=False),
    sa.Column('primary_entity_type', sa.String(), nullable=False),
    sa.Column('primary_entity_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('correlation_reason', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_correlation_groups_group_key'), 'alert_correlation_groups', ['group_key'], unique=True)
    op.create_index(op.f('ix_alert_correlation_groups_primary_entity_id'), 'alert_correlation_groups', ['primary_entity_id'], unique=False)
    op.create_table('case_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=False),
    sa.Column('source_entity_type', sa.String(), nullable=False),
    sa.Column('source_entity_id', sa.String(), nullable=False),
    sa.Column('relevance', sa.String(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('deduplication_key', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('trigger_reason', sa.String(), nullable=True),
    sa.Column('correlation_group_id', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.id'], ),
    sa.ForeignKeyConstraint(['correlation_group_id'], ['alert_correlation_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_deduplication_key'), 'alerts', ['deduplication_key'], unique=True)
    op.create_index(op.f('ix_alerts_entity_id'), 'alerts', ['entity_id'], unique=False)
    op.create_index(op.f('ix_alerts_entity_type'), 'alerts', ['entity_type'], unique=False)
    op.create_table('alert_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('previous_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('case_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_events',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('case_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('case_events_pkey'))
    )
    op.drop_table('alert_history')
    op.drop_index(op.f('ix_alerts_entity_type'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_entity_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_deduplication_key'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('case_notes')
    op.drop_table('case_evidence')
    op.drop_table('case_actions')
    op.drop_index(op.f('ix_alert_correlation_groups_primary_entity_id'), table_name='alert_correlation_groups')
    op.drop_index(op.f('ix_alert_correlation_groups_group_key'), table_name='alert_correlation_groups')
    op.drop_table('alert_correlation_groups')
    op.drop_index(op.f('ix_investigation_cases_primary_entity_type'), table_name='investigation_cases')
    op.drop_index(op.f('ix_investigation_cases_primary_entity_id'), table_name='investigation_cases')
    op.drop_index(op.f('ix_investigation_cases_case_number'), table_name='investigation_cases')
    op.drop_table('investigation_cases')
    # ### end Alembic commands ###
