"""phase_14_fix

Revision ID: 8e0a240f778e
Revises: fd8d50090fe7
Create Date: 2026-10-01 16:38:11.988223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e0a240f778e'
down_revision: Union[str, Sequence[str], None] = 'fd8d50090fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_evolution_snapshots', sa.Column('snapshot_metadata', sa.JSON(), nullable=True))
    op.drop_column('risk_evolution_snapshots', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_evolution_snapshots', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('risk_evolution_snapshots', 'snapshot_metadata')
    # ### end Alembic commands ###
