"""Phase 7 Graph Tables

Revision ID: de7a68e63472
Revises: 7ec14f6ded63
Create Date: 2026-10-01 13:50:30.470803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7a68e63472'
down_revision: Union[str, Sequence[str], None] = '7ec14f6ded63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graph_edges', sa.Column('weight', sa.Float(), nullable=False))
    op.add_column('graph_edges', sa.Column('count', sa.Integer(), nullable=False))
    op.add_column('graph_edges', sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False))
    op.add_column('graph_edges', sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False))
    op.create_unique_constraint('uix_graph_edge', 'graph_edges', ['source_node_id', 'target_node_id', 'relationship_type'])
    op.create_unique_constraint('uix_graph_node_type_entity', 'graph_nodes', ['node_type', 'entity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_graph_node_type_entity', 'graph_nodes', type_='unique')
    op.drop_constraint('uix_graph_edge', 'graph_edges', type_='unique')
    op.drop_column('graph_edges', 'last_seen')
    op.drop_column('graph_edges', 'first_seen')
    op.drop_column('graph_edges', 'count')
    op.drop_column('graph_edges', 'weight')
    # ### end Alembic commands ###
