"""phase_13_monitoring_governance

Revision ID: e10d2debdb83
Revises: 28c9227b424d
Create Date: 2026-10-01 16:02:03.690817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e10d2debdb83'
down_revision: Union[str, Sequence[str], None] = '28c9227b424d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('null_rate', sa.Float(), nullable=True),
    sa.Column('invalid_rate', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_results_feature'), 'data_quality_results', ['feature'], unique=False)
    op.create_table('drift_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('baseline_window', sa.String(), nullable=False),
    sa.Column('comparison_window', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drift_results_feature'), 'drift_results', ['feature'], unique=False)
    op.create_table('governance_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_events_actor'), 'governance_events', ['actor'], unique=False)
    op.create_table('model_lineage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('feature_version', sa.String(), nullable=True),
    sa.Column('policy_version', sa.String(), nullable=True),
    sa.Column('prediction', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_lineage_correlation_id'), 'model_lineage', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_model_lineage_model_id'), 'model_lineage', ['model_id'], unique=False)
    op.create_table('monitoring_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('affected_component', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_alerts_severity'), 'monitoring_alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_monitoring_alerts_status'), 'monitoring_alerts', ['status'], unique=False)
    op.create_table('monitoring_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('service', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_metrics_metric_type'), 'monitoring_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_monitoring_metrics_name'), 'monitoring_metrics', ['name'], unique=False)
    op.create_index(op.f('ix_monitoring_metrics_service'), 'monitoring_metrics', ['service'], unique=False)
    op.create_index(op.f('ix_monitoring_metrics_timestamp'), 'monitoring_metrics', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitoring_metrics_timestamp'), table_name='monitoring_metrics')
    op.drop_index(op.f('ix_monitoring_metrics_service'), table_name='monitoring_metrics')
    op.drop_index(op.f('ix_monitoring_metrics_name'), table_name='monitoring_metrics')
    op.drop_index(op.f('ix_monitoring_metrics_metric_type'), table_name='monitoring_metrics')
    op.drop_table('monitoring_metrics')
    op.drop_index(op.f('ix_monitoring_alerts_status'), table_name='monitoring_alerts')
    op.drop_index(op.f('ix_monitoring_alerts_severity'), table_name='monitoring_alerts')
    op.drop_table('monitoring_alerts')
    op.drop_index(op.f('ix_model_lineage_model_id'), table_name='model_lineage')
    op.drop_index(op.f('ix_model_lineage_correlation_id'), table_name='model_lineage')
    op.drop_table('model_lineage')
    op.drop_index(op.f('ix_governance_events_actor'), table_name='governance_events')
    op.drop_table('governance_events')
    op.drop_index(op.f('ix_drift_results_feature'), table_name='drift_results')
    op.drop_table('drift_results')
    op.drop_index(op.f('ix_data_quality_results_feature'), table_name='data_quality_results')
    op.drop_table('data_quality_results')
    # ### end Alembic commands ###
