"""phase_14

Revision ID: fd8d50090fe7
Revises: ce7d39108138
Create Date: 2026-10-01 16:37:58.965321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8d50090fe7'
down_revision: Union[str, Sequence[str], None] = 'ce7d39108138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('feedback_type', sa.String(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competition_feedback_created_by'), 'competition_feedback', ['created_by'], unique=False)
    op.create_index(op.f('ix_competition_feedback_target_id'), 'competition_feedback', ['target_id'], unique=False)
    op.create_table('decision_replays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_evaluation_id', sa.UUID(), nullable=True),
    sa.Column('replay_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replayed_score', sa.Float(), nullable=True),
    sa.Column('replayed_signals', sa.JSON(), nullable=True),
    sa.Column('replayed_rules', sa.JSON(), nullable=True),
    sa.Column('divergence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_replays_original_evaluation_id'), 'decision_replays', ['original_evaluation_id'], unique=False)
    op.create_table('intelligence_fusion_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('fusion_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aggregated_context', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intelligence_fusion_records_entity_id'), 'intelligence_fusion_records', ['entity_id'], unique=False)
    op.create_table('risk_evolution_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delta_1h', sa.Float(), nullable=True),
    sa.Column('delta_24h', sa.Float(), nullable=True),
    sa.Column('delta_7d', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_evolution_snapshots_entity_id'), 'risk_evolution_snapshots', ['entity_id'], unique=False)
    op.create_table('simulation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('run_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('baseline_comparison', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threat_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_signals_entity_id'), 'threat_signals', ['entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_signals_entity_id'), table_name='threat_signals')
    op.drop_table('threat_signals')
    op.drop_table('simulation_runs')
    op.drop_index(op.f('ix_risk_evolution_snapshots_entity_id'), table_name='risk_evolution_snapshots')
    op.drop_table('risk_evolution_snapshots')
    op.drop_index(op.f('ix_intelligence_fusion_records_entity_id'), table_name='intelligence_fusion_records')
    op.drop_table('intelligence_fusion_records')
    op.drop_index(op.f('ix_decision_replays_original_evaluation_id'), table_name='decision_replays')
    op.drop_table('decision_replays')
    op.drop_index(op.f('ix_competition_feedback_target_id'), table_name='competition_feedback')
    op.drop_index(op.f('ix_competition_feedback_created_by'), table_name='competition_feedback')
    op.drop_table('competition_feedback')
    # ### end Alembic commands ###
